export default {
  ADD_GRUDGE: "ADD_GRUDGE",
  EDIT_GRUDGE: "EDIT_GRUDGE",
  UNDO: "UNDO",
  REDO: "REDO",
  LOADING: "LOADING",
  FETCHING_COMPLETED: "FETCHING_COMPLETED",
  FETCHING_ERROR: "FETCHING_ERROR"
};
